import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

# Define Colleges Data
colleges = [
    {
        "name": "Andhra University College of Engineering (Autonomous), Visakhapatnam",
        "location": "Visakhapatnam, Andhra Pradesh",
        "website": "https://www.andhrauniversity.edu.in",
        "accreditation": "AICTE Approved, NBA Accredited",
        "naac": "NAAC A++ Grade",
        "nirf": "NIRF Rank: 94",
        "type": "Government",
        "courses": "B.Tech, M.Tech, MCA",
        "branches": "CSE, AI&DS, ECE, EEE, ME, CE, Chem, IT",
        "intake": "CSE: 120, ECE: 120, EEE: 100, ME: 100, CE: 100",
        "fees": "CSE: ₹15,000/year (Regular), ₹50,000/year (Self-Finance)",
        "hostel_fee": "Hostel Fee: ₹30,000/year (including mess)",
        "additional_charges": "Additional Charges: ₹5,000/year (Library & Exams)",
        "eligibility": "Intermediate (10+2) MPC with minimum 45% marks",
        "accepted_exams": "AP EAPCET / AP EAMCET",
        "admission_process": "Admissions through state counseling (Convenor Quota)",
        "cutoffs": "CSE: 850 (Gen), ECE: 2200 (Gen), EEE: 4500 (Gen), ME: 6800 (Gen), CE: 9000 (Gen)",
        "placements_avg": "₹7.5 LPA",
        "placements_highest": "₹32.0 LPA",
        "placements_pct": "88%",
        "recruiters": "TCS, Infosys, Wipro, Cognizant, Amazon, Oracle",
        "scholarships": "Merit-based scholarships, full Jagananna Vidya Deevena fee reimbursement eligible, sports quota waiver"
    },
    {
        "name": "JNTUK College of Engineering, Kakinada",
        "location": "Kakinada, Andhra Pradesh",
        "website": "https://www.jntukucek.ac.in",
        "accreditation": "AICTE Approved, NBA Accredited",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 110",
        "type": "Government",
        "courses": "B.Tech, M.Tech, MCA",
        "branches": "CSE, ECE, EEE, ME, CE, CSE-AI&ML, Chemical",
        "intake": "CSE: 60, CSE-AI&ML: 60, ECE: 60, EEE: 60, ME: 60",
        "fees": "CSE: ₹10,000/year (Regular), ₹45,000/year (Self-Finance)",
        "hostel_fee": "Hostel Fee: ₹28,000/year",
        "additional_charges": "Additional Charges: ₹4,000/year",
        "eligibility": "10+2 MPC with 45% marks",
        "accepted_exams": "AP EAPCET",
        "admission_process": "AP EAPCET counseling option entry",
        "cutoffs": "CSE: 1200 (Gen), CSE-AI&ML: 1800 (Gen), ECE: 3000 (Gen), EEE: 5500 (Gen), ME: 8000 (Gen)",
        "placements_avg": "₹6.8 LPA",
        "placements_highest": "₹28.0 LPA",
        "placements_pct": "85%",
        "recruiters": "L&T, TCS, Wipro, ACC, Microsoft, Cisco",
        "scholarships": "Jagananna Vidya Deevena (JVD) eligibility, State Merit Scholarships"
    },
    {
        "name": "JNTUA College of Engineering, Anantapur",
        "location": "Anantapur, Andhra Pradesh",
        "website": "https://www.jntuaceam.ac.in",
        "accreditation": "AICTE Approved, NBA Accredited",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 135",
        "type": "Government",
        "courses": "B.Tech, M.Tech",
        "branches": "CSE, ECE, EEE, ME, CE, Chemical",
        "intake": "CSE: 60, ECE: 60, EEE: 60, ME: 60, CE: 60",
        "fees": "CSE/ECE/EEE: ₹10,000/year (Regular)",
        "hostel_fee": "Hostel Fee: ₹25,000/year",
        "additional_charges": "Additional Charges: ₹3,500/year",
        "eligibility": "10+2 MPC stream with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE Single Window Counseling",
        "cutoffs": "CSE: 2800 (Gen), ECE: 4500 (Gen), EEE: 7500 (Gen), ME: 11000 (Gen), CE: 14000 (Gen)",
        "placements_avg": "₹5.5 LPA",
        "placements_highest": "₹18.0 LPA",
        "placements_pct": "80%",
        "recruiters": "TCS, Cognizant, Accenture, Hexaware, Hyundai",
        "scholarships": "Full State Fee Reimbursement, Jagananna Vasathi Deevena support"
    },
    {
        "name": "Sri Venkateswara University College of Engineering (SVUCE), Tirupati",
        "location": "Tirupati, Andhra Pradesh",
        "website": "https://www.svuce.edu.in",
        "accreditation": "AICTE Approved, NBA Accredited",
        "naac": "NAAC A++ Grade",
        "nirf": "NIRF Rank: 105",
        "type": "Government",
        "courses": "B.Tech, M.Tech",
        "branches": "CSE, ECE, EEE, ME, CE, EIE, Chemical",
        "intake": "CSE: 60, ECE: 60, EEE: 60, ME: 60, CE: 60",
        "fees": "B.Tech branches: ₹15,000/year (Regular)",
        "hostel_fee": "Hostel Fee: ₹32,000/year",
        "additional_charges": "Additional Charges: ₹4,500/year",
        "eligibility": "Intermediate MPC with minimum 45% marks",
        "accepted_exams": "AP EAPCET",
        "admission_process": "AP EAPCET Single Window Web Counseling",
        "cutoffs": "CSE: 2000 (Gen), ECE: 3800 (Gen), EEE: 6200 (Gen), ME: 9500 (Gen), CE: 12000 (Gen)",
        "placements_avg": "₹6.2 LPA",
        "placements_highest": "₹22.0 LPA",
        "placements_pct": "82%",
        "recruiters": "CTS, Wipro, Infosys, Tech Mahindra, L&T, Yahoo",
        "scholarships": "JVD Fee Reimbursement, Merit Scholarships, SVU Alumni Scholarships"
    },
    {
        "name": "Velagapudi Ramakrishna Siddhartha Engineering College (VRSEC), Vijayawada",
        "location": "Vijayawada, Andhra Pradesh",
        "website": "https://www.vrsiddhartha.ac.in",
        "accreditation": "AICTE Approved, NBA Accredited (All Branches)",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 141",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, IT, ECE, EEE, ME, CE, CSE-AI&ML, CSE-Data Science",
        "intake": "CSE: 240, CSE-AIML: 120, IT: 120, ECE: 240, EEE: 120",
        "fees": "B.Tech: ₹70,000/year (Convenor Quota), ₹2,10,000/year (B-Category)",
        "hostel_fee": "Hostel Fee: ₹65,000/year",
        "additional_charges": "Additional Charges: ₹12,000/year (Transit & Lab fees)",
        "eligibility": "10+2 MPC with 45% minimum",
        "accepted_exams": "AP EAPCET, JEE Main",
        "admission_process": "70% seats Category-A (EAPCET counseling), 30% Category-B (Management/JEE)",
        "cutoffs": "CSE: 4200 (Gen), CSE-AIML: 5500 (Gen), ECE: 9500 (Gen), EEE: 18000 (Gen), ME: 28000 (Gen)",
        "placements_avg": "₹5.8 LPA",
        "placements_highest": "₹44.0 LPA (Adobe)",
        "placements_pct": "92%",
        "recruiters": "Amazon, Microsoft, TCS Ninja/Digital, Capgemini, Cognizant",
        "scholarships": "JVD eligible (Category-A), Siddhartha Academy Merit Scholarships, fee waiver for top rankers"
    },
    {
        "name": "Gayatri Vidya Parishad College of Engineering (GVP), Visakhapatnam",
        "location": "Visakhapatnam, Andhra Pradesh",
        "website": "https://www.gvpce.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A Grade (CGPA 3.47/4.0)",
        "nirf": "NIRF Rank: 151-200 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MCA",
        "branches": "CSE, IT, ECE, EEE, ME, CE, Chemical, CSE-AI&ML",
        "intake": "CSE: 240, ECE: 240, IT: 180, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹69,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹70,000/year",
        "additional_charges": "Additional Charges: ₹8,000/year",
        "eligibility": "10+2 MPC with 45% marks in group subjects",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Convenor Quota (70% via counseling), Management Quota (30% merit)",
        "cutoffs": "CSE: 3500 (Gen), CSE-AIML: 4800 (Gen), ECE: 8500 (Gen), EEE: 16000 (Gen), ME: 25000 (Gen)",
        "placements_avg": "₹6.0 LPA",
        "placements_highest": "₹30.0 LPA",
        "placements_pct": "90%",
        "recruiters": "Amazon, TCS, CTS, Wipro, Soliton, L&T, Infosys",
        "scholarships": "JVD eligible (Full fee reimbursement for eligible category), GVP Alumni Scholarships"
    },
    {
        "name": "VIT-AP University, Amaravati",
        "location": "Amaravati, Andhra Pradesh",
        "website": "https://vitap.ac.in",
        "accreditation": "UGC Recognized, Private State University",
        "naac": "NAAC A+ Grade",
        "nirf": "Part of VIT Group (NIRF Rank: 11 in Engineering overall)",
        "type": "Private University",
        "courses": "B.Tech, M.Tech integrated, BBA, Law, Ph.D",
        "branches": "CSE, CSE-AI&ML, CSE-Data Science, CSE-Cyber Security, ECE, ECE-VLSI",
        "intake": "CSE: 1200, CSE-AIML: 600, ECE: 300",
        "fees": "Category 1: ₹2,01,000/year, Category 2: ₹2,95,000/year, Category 3: ₹3,95,000/year",
        "hostel_fee": "Hostel Fee: ₹95,000 to ₹1,40,000/year (based on A/C and room capacity)",
        "additional_charges": "Additional Charges: ₹15,000/year (Exam & Caution Deposit)",
        "eligibility": "Intermediate MPC with 60% average in Maths, Physics, Chemistry",
        "accepted_exams": "VITEEE, AP EAPCET (limited seats via counseling), JEE Main",
        "admission_process": "Admissions primarily through VITEEE counseling, small quota through AP EAPCET counseling",
        "cutoffs": "VITEEE rank under 25000 for CSE Cat-1, AP EAPCET rank under 8000 for Convenor Quota",
        "placements_avg": "₹8.0 LPA",
        "placements_highest": "₹63.0 LPA (Motorola)",
        "placements_pct": "94%",
        "recruiters": "Intel, Microsoft, Amazon, eBay, Dell, TCS, Cognizant",
        "scholarships": "VITEEE Rank Holders Scholarship (up to 100%), AP District Toppers Fee Waiver (100% waiver)"
    },
    {
        "name": "SRM University AP, Amaravati",
        "location": "Amaravati, Andhra Pradesh",
        "website": "https://srmap.edu.in",
        "accreditation": "UGC Recognized, Private State University",
        "naac": "NAAC A+ Grade",
        "nirf": "Part of SRM Group (NIRF Rank: 28 in Engineering)",
        "type": "Private University",
        "courses": "B.Tech, B.Sc, BBA, MBA, Ph.D",
        "branches": "CSE, CSE-AI&ML, CSE-Data Science, ECE, EEE, ME, CE",
        "intake": "CSE: 1000, ECE: 200, EEE: 60, ME: 60",
        "fees": "B.Tech CSE: ₹2,50,000/year, ECE/EEE: ₹1,75,000/year",
        "hostel_fee": "Hostel Fee: ₹1,10,000 to ₹1,50,000/year",
        "additional_charges": "Additional Charges: ₹10,000/year",
        "eligibility": "10+2 MPC with minimum 60% aggregate marks",
        "accepted_exams": "SRMJEEE, JEE Main, AP EAPCET",
        "admission_process": "SRMJEEE exam counseling or Merit-based direct entry (JEE / EAPCET)",
        "cutoffs": "SRMJEEE rank under 15000 for CSE, AP EAPCET rank under 10000 for Merit concession",
        "placements_avg": "₹7.8 LPA",
        "placements_highest": "₹50.0 LPA",
        "placements_pct": "95%",
        "recruiters": "Amazon, Google, PayPal, Barclays, TCS, Wipro, Optum",
        "scholarships": "SRM Founder's Scholarship (100% waiver for EAPCET < 1000 or JEE > 99%), Merit Scholarships (25%-75% discount)"
    },
    {
        "name": "Koneru Lakshmaiah Education Foundation (KL University), Vaddeswaram",
        "location": "Green Fields, Vaddeswaram, Guntur District, Andhra Pradesh – 522502",
        "website": "https://www.kluniversity.in",
        "accreditation": "AICTE Approved, Category-1 Deemed University",
        "naac": "NAAC A++ Grade",
        "nirf": "NIRF Rank: 44 (Engineering)",
        "type": "Private Deemed University",
        "courses": "B.Tech, M.Tech, B.Arch, MBA, MCA, Ph.D",
        "branches": "CSE, CSIT, AI&DS, AI&ML, Data Science, Cyber Security, ECE, EEE, ME, CE",
        "intake": "CSE: 1500, ECE: 400, EEE: 120, ME: 120",
        "fees": "B.Tech CSE/AI&DS/AI&ML/Data Science/Cyber Security: ₹2,75,000–₹2,95,000/year, ECE: ₹2,55,000/year, EEE/ME: ₹2,35,000–₹2,40,000/year, CE: ₹2,30,000/year",
        "hostel_fee": "Hostel Fee: ₹90,000 to ₹1,30,000/year",
        "additional_charges": "Admission Fee (One-Time): ₹16,000",
        "eligibility": "10+2 MPC with 60% aggregate and 60% in group subjects",
        "accepted_exams": "KLEEE, JEE Main, AP EAPCET",
        "admission_process": "KLEEE exam counseling, JEE and EAPCET ranks accepted for direct counseling",
        "cutoffs": "KLEEE Rank 1–100: 100% scholarship, AP EAPCET Rank 1–1000: 50%, 1001–5000: 25%, 5001–10000: 15%, 10001–15000: 10%",
        "placements_avg": "₹9.5 LPA",
        "placements_highest": "₹75.0 LPA",
        "placements_pct": "90%",
        "recruiters": "Amazon, Microsoft, Google, Deloitte, Accenture, TCS, Infosys, Cognizant, IBM, Capgemini",
        "scholarships": "KLEEE Rank 1–100: 100%, 101–1000: 50–75%, 1001–5000: 25–35%, 5001–15000: 10–15%; JEE 95+%ile: 100%; AP EAPCET Rank 1–1000: 50%; Board Toppers: up to 100%; SC/ST/OBC fee concessions"
    },
    {
        "name": "GITAM Deemed to be University, Visakhapatnam",
        "location": "Rushikonda, Visakhapatnam, Andhra Pradesh – 530045",
        "website": "https://www.gitam.edu",
        "accreditation": "AICTE Approved, UGC Deemed University",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 101-150 Band",
        "type": "Private Deemed University",
        "courses": "B.Tech, M.Tech, B.Pharm, MBA, Medicine, Law",
        "branches": "CSE, CSE-AI&ML, CSE-Cyber Security, CSE-Data Science, ECE, ECE-VLSI, Robotics & AI, Biomedical, Biotechnology, EEE, ME, CE",
        "intake": "CSE: 1200, ECE: 300, EEE: 60, ME: 60",
        "fees": "B.Tech CSE/CSE-AI&ML/Cyber Security/Data Science: ₹4,05,000/year, ECE/Biotech/Biomedical/Robotics: ₹3,06,000/year, CE/EEE/ME: ₹1,98,000/year",
        "hostel_fee": "Hostel Fee: ₹95,000 to ₹1,40,000/year",
        "additional_charges": "Additional Charges: ₹12,000/year",
        "eligibility": "10+2 MPC with 60% marks in Math, Physics, Chemistry",
        "accepted_exams": "GAT (GITAM Admission Test), JEE Main, AP EAPCET",
        "admission_process": "GAT exam counseling; JEE ≥98%ile or EAPCET Rank ≤250: 100% scholarship; direct counseling for EAPCET rankers",
        "cutoffs": "GAT Rank ≤50: 100%, 51–250: 75%, 251–1000: 50%, 1001–3000: 25%; AP EAPCET Rank ≤250: 100%, 251–1000: 75%, 1001–5000: 50%, 5001–25000: 25%",
        "placements_avg": "₹6.0 LPA",
        "placements_highest": "₹46.0 LPA",
        "placements_pct": "85%",
        "recruiters": "Microsoft, Amazon, Deloitte, Accenture, TCS, Infosys, Cognizant, Wipro, Capgemini, IBM",
        "scholarships": "GAT Rank ≤50: 100% tuition waiver; JEE ≥98%ile or EAPCET ≤250: 100%; EAPCET 251–1000: 75%; EAPCET 1001–5000: 50%; EAPCET 5001–25000: 25%; SC/ST/OBC/EWS concessions; Sports quota scholarships"
    },
    {
        "name": "RVR & JC College of Engineering, Guntur",
        "location": "Guntur, Andhra Pradesh",
        "website": "https://www.rvrjcce.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 151-200 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE, Chemical",
        "intake": "CSE: 180, ECE: 180, IT: 120, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹68,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹60,000/year",
        "additional_charges": "Additional Charges: ₹7,000/year",
        "eligibility": "10+2 MPC with 45% marks",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Convenor counseling Category-A (70%), Management Category-B (30%)",
        "cutoffs": "CSE: 5200 (Gen), CSE-AIML: 7000 (Gen), ECE: 11000 (Gen), EEE: 20000 (Gen), ME: 32000 (Gen)",
        "placements_avg": "₹5.2 LPA",
        "placements_highest": "₹24.0 LPA",
        "placements_pct": "89%",
        "recruiters": "TCS Ninja/Digital, Cognizant, Wipro, Capgemini, Accenture",
        "scholarships": "Full JVD eligibility for qualified Category-A students, Merit awards for class toppers"
    },
    {
        "name": "Anil Neerukonda Institute of Technology & Sciences (ANITS), Visakhapatnam",
        "location": "Visakhapatnam, Andhra Pradesh",
        "website": "https://www.anits.edu.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 201-250 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE, Chemical",
        "intake": "CSE: 240, IT: 180, ECE: 240, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹66,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹68,000/year",
        "additional_charges": "Additional Charges: ₹6,500/year",
        "eligibility": "10+2 MPC with minimum 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE counseling Category-A, Management Category-B via notifications",
        "cutoffs": "CSE: 5800 (Gen), CSE-AIML: 7800 (Gen), ECE: 12000 (Gen), EEE: 22000 (Gen), ME: 35000 (Gen)",
        "placements_avg": "₹4.8 LPA",
        "placements_highest": "₹20.0 LPA",
        "placements_pct": "86%",
        "recruiters": "Infosys, Wipro, Cognizant, AWS, TCS, Capgemini, Musigma",
        "scholarships": "JVD government scheme benefits, college merit concessions for ranks < 5000 in EAPCET"
    },
    {
        "name": "Madanapalle Institute of Technology & Science (MITS), Madanapalle",
        "location": "Chittoor District, Andhra Pradesh",
        "website": "https://www.mits.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 201-250 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI, CSE-DS, CSE-CS, ECE, EEE, ME, CE",
        "intake": "CSE: 240, CSE-AI: 180, ECE: 240, EEE: 120",
        "fees": "B.Tech: ₹70,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹58,000/year",
        "additional_charges": "Additional Charges: ₹5,000/year",
        "eligibility": "10+2 MPC with 45% minimum",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE Convenor Counseling (Category-A)",
        "cutoffs": "CSE: 12000 (Gen), CSE-AI: 16000 (Gen), ECE: 24000 (Gen), EEE: 38000 (Gen), ME: 50000 (Gen)",
        "placements_avg": "₹4.6 LPA",
        "placements_highest": "₹24.0 LPA",
        "placements_pct": "85%",
        "recruiters": "TCS, LTI, Cognizant, Wipro, Capgemini, KPIT",
        "scholarships": "JVD scheme eligible, minority scholarships support, sports quota waivers"
    },
    {
        "name": "Prasad V. Potluri Siddhartha Institute of Technology (PVPSIT), Vijayawada",
        "location": "Vijayawada, Andhra Pradesh",
        "website": "http://www.pvpsiddhartha.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 201-250 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 180, IT: 120, ECE: 120, EEE: 120, ME: 60",
        "fees": "B.Tech: ₹67,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹62,000/year",
        "additional_charges": "Additional Charges: ₹7,500/year",
        "eligibility": "10+2 MPC with 45% group percentage",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Category-A counseling (70%) and Category-B administration (30%)",
        "cutoffs": "CSE: 6500 (Gen), CSE-AIML: 8500 (Gen), ECE: 13000 (Gen), EEE: 24000 (Gen), ME: 38000 (Gen)",
        "placements_avg": "₹4.9 LPA",
        "placements_highest": "₹22.0 LPA",
        "placements_pct": "87%",
        "recruiters": "Capgemini, Cognizant, Wipro, TCS, Mindtree, Virtusa",
        "scholarships": "Siddhartha Academy concessions, full JVD government reimbursement eligibility"
    },
    {
        "name": "Sree Vidyanikethan Engineering College (Mohan Babu University), Tirupati",
        "location": "Tirupati, Andhra Pradesh",
        "website": "https://svec.education",
        "accreditation": "AICTE Approved, NBA Accredited",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 151-200 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 240, IT: 180, ECE: 240, EEE: 120",
        "fees": "B.Tech: ₹70,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹75,000/year",
        "additional_charges": "Additional Charges: ₹9,000/year",
        "eligibility": "10+2 MPC with minimum 45% marks",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Convenor counseling or Category-B application through official website",
        "cutoffs": "CSE: 8500 (Gen), CSE-AIML: 10500 (Gen), ECE: 16000 (Gen), EEE: 28000 (Gen), ME: 42000 (Gen)",
        "placements_avg": "₹5.0 LPA",
        "placements_highest": "₹25.0 LPA",
        "placements_pct": "88%",
        "recruiters": "Wipro, Cognizant, Hexaware, Hyundai, TCS, Amazon",
        "scholarships": "MBU Merit Scholarships, Jagananna Vidya Deevena support for local students"
    },
    {
        "name": "Vasireddy Venkatadri Institute of Technology (VVIT), Guntur",
        "location": "Nambur, Guntur, Andhra Pradesh",
        "website": "https://www.vvitguntur.com",
        "accreditation": "AICTE Approved, NBA Accredited (CSE, ECE, IT, EEE)",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 251-300 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, CSE-IoT, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 240, IT: 180, ECE: 240, EEE: 120, ME: 60",
        "fees": "B.Tech: ₹60,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹58,000/year",
        "additional_charges": "Additional Charges: ₹6,000/year",
        "eligibility": "10+2 MPC with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE state counseling online option entry",
        "cutoffs": "CSE: 7500 (Gen), CSE-AIML: 9800 (Gen), ECE: 15000 (Gen), EEE: 26000 (Gen), ME: 45000 (Gen)",
        "placements_avg": "₹4.7 LPA",
        "placements_highest": "₹18.0 LPA",
        "placements_pct": "87%",
        "recruiters": "TCS Ninja, Infosys, Cognizant, Wipro, Capgemini, EPAM",
        "scholarships": "JVD eligibility, VVIT Merit concessions for rankers below 8000"
    },
    {
        "name": "Laki Reddy Bali Reddy College of Engineering (LBRCE), Mylavaram",
        "location": "Krishna District, Mylavaram, Andhra Pradesh",
        "website": "https://www.lbrce.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 201-250 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, IT, ECE, EEE, ME, CE, Aerospace",
        "intake": "CSE: 180, IT: 120, ECE: 180, EEE: 90, Aerospace: 60",
        "fees": "B.Tech: ₹65,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹55,000/year",
        "additional_charges": "Additional Charges: ₹5,500/year",
        "eligibility": "10+2 MPC with group aggregate of 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE single window counseling Convenor quota",
        "cutoffs": "CSE: 9500 (Gen), CSE-AIML: 12500 (Gen), ECE: 18500 (Gen), EEE: 32000 (Gen), Aerospace: 45000 (Gen)",
        "placements_avg": "₹4.5 LPA",
        "placements_highest": "₹16.0 LPA",
        "placements_pct": "84%",
        "recruiters": "Wipro, Cognizant, Mindtree, TCS, Hexaware, Hyundai Transys",
        "scholarships": "Government fee reimbursement via JVD, LBRCE merit schemes"
    },
    {
        "name": "Maharaj Vijayaram Gajapathi Raj (MVGR) College of Engineering, Vizianagaram",
        "location": "Vizianagaram, Andhra Pradesh",
        "website": "https://www.mvgrce.edu.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 201-250 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA",
        "branches": "CSE, CSE-AI&ML, IT, ECE, EEE, ME, CE, Chemical",
        "intake": "CSE: 180, IT: 120, ECE: 180, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹67,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹60,000/year",
        "additional_charges": "Additional Charges: ₹6,000/year",
        "eligibility": "10+2 MPC with 45% in groups",
        "accepted_exams": "AP EAPCET",
        "admission_process": "70% seat allocation via state counseling portal, 30% management",
        "cutoffs": "CSE: 8200 (Gen), CSE-AIML: 10800 (Gen), ECE: 16500 (Gen), EEE: 28000 (Gen), ME: 40000 (Gen)",
        "placements_avg": "₹4.8 LPA",
        "placements_highest": "₹21.0 LPA",
        "placements_pct": "86%",
        "recruiters": "Cognizant, TCS, Wipro, Capgemini, Salesforce, L&T",
        "scholarships": "JVD reimbursement schemes, college alumni scholarships"
    },
    {
        "name": "Pragati Engineering College, Surampalem",
        "location": "East Godavari District, Surampalem, Andhra Pradesh",
        "website": "https://pragati.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 251-300 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 180, IT: 120, ECE: 180, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹63,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹54,000/year",
        "additional_charges": "Additional Charges: ₹5,000/year",
        "eligibility": "10+2 MPC with minimum 45% group marks",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE state counseling online option entry",
        "cutoffs": "CSE: 12500 (Gen), CSE-AIML: 15500 (Gen), ECE: 22000 (Gen), EEE: 38000 (Gen), ME: 52000 (Gen)",
        "placements_avg": "₹4.2 LPA",
        "placements_highest": "₹15.0 LPA",
        "placements_pct": "82%",
        "recruiters": "TCS Ninja, Wipro, Capgemini, Infosys, Tech Mahindra",
        "scholarships": "JVD government scheme, college fee concessions for poor meritorious students"
    },
    {
        "name": "Aditya Engineering College, Surampalem",
        "location": "Surampalem, East Godavari, Andhra Pradesh",
        "website": "https://www.aec.edu.in",
        "accreditation": "AICTE Approved, Autonomous, NBA (CSE, ECE, ME)",
        "naac": "NAAC A+ Grade (CGPA 3.53/4.0)",
        "nirf": "NIRF Rank: 151-200 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE, Agricultural, Petroleum",
        "intake": "CSE: 240, IT: 120, ECE: 240, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹65,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹65,000/year",
        "additional_charges": "Additional Charges: ₹7,000/year",
        "eligibility": "10+2 MPC with aggregate group of 45%",
        "accepted_exams": "AP EAPCET, JEE Main",
        "admission_process": "Category-A state web option counseling, Category-B direct administrative admission",
        "cutoffs": "CSE: 10500 (Gen), CSE-AIML: 13500 (Gen), ECE: 19500 (Gen), EEE: 34000 (Gen), ME: 48000 (Gen)",
        "placements_avg": "₹4.5 LPA",
        "placements_highest": "₹31.3 LPA",
        "placements_pct": "86%",
        "recruiters": "Amazon, DXC Technology, TCS, Tech Mahindra, ValueLabs, LTI",
        "scholarships": "Aditya Merit scholarships, JVD full fee reimbursement concessions"
    },
    {
        "name": "SRKR Engineering College, Bhimavaram",
        "location": "Bhimavaram, West Godavari, Andhra Pradesh",
        "website": "https://www.srkrengg.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 151-200 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, PhD",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 300, ECE: 240, IT: 180, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹70,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹62,000/year",
        "additional_charges": "Additional Charges: ₹8,000/year",
        "eligibility": "10+2 MPC stream with minimum 45% group average",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Convenor state counseling list selection",
        "cutoffs": "CSE: 5000 (Gen), CSE-AIML: 6800 (Gen), ECE: 10500 (Gen), EEE: 19000 (Gen), ME: 30000 (Gen)",
        "placements_avg": "₹5.3 LPA",
        "placements_highest": "₹28.0 LPA",
        "placements_pct": "91%",
        "recruiters": "TCS Ninja/Digital, Cognizant, Wipro, Soliton, Amazon, Capgemini",
        "scholarships": "JVD government reimbursement, SRKR Golden Jubilee Alumni awards"
    },
    {
        "name": "Vishnu Institute of Technology (VITB), Bhimavaram",
        "location": "Bhimavaram, Andhra Pradesh",
        "website": "https://vishnu.edu.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade (CGPA 3.51/4.0)",
        "nirf": "NIRF Rank: 151-200 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA",
        "branches": "CSE, CSE-AI&ML, CSE-AI&DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 240, IT: 180, ECE: 240, EEE: 120, ME: 60",
        "fees": "B.Tech: ₹70,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹65,000/year",
        "additional_charges": "Additional Charges: ₹8,500/year",
        "eligibility": "10+2 MPC with 45% marks in groups",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE state counseling online option entry",
        "cutoffs": "CSE: 5800 (Gen), CSE-AIML: 7500 (Gen), ECE: 11500 (Gen), EEE: 21000 (Gen), ME: 33000 (Gen)",
        "placements_avg": "₹5.5 LPA",
        "placements_highest": "₹41.0 LPA (Adobe)",
        "placements_pct": "92%",
        "recruiters": "Adobe, Expedia, TCS Digital, Cognizant, Wipro, Capgemini",
        "scholarships": "Sri Vishnu Society Merit Scholarships, JVD state reimbursement schemes"
    },
    {
        "name": "Shri Vishnu Engineering College for Women (SVECW), Bhimavaram",
        "location": "Bhimavaram, Andhra Pradesh",
        "website": "https://www.svecw.edu.in",
        "accreditation": "AICTE Approved, NBA (CSE, ECE, EEE, IT), Women-Only",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 101-150 Band",
        "type": "Private Autonomous (Women)",
        "courses": "B.Tech, M.Tech, MBA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 300, IT: 180, ECE: 240, EEE: 120",
        "fees": "B.Tech: ₹70,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹60,000/year",
        "additional_charges": "Additional Charges: ₹8,000/year",
        "eligibility": "10+2 MPC, Female candidates with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "State web counseling Convenor Quota (Women Category-A)",
        "cutoffs": "CSE: 5200 (Gen), CSE-AIML: 6900 (Gen), ECE: 10800 (Gen), EEE: 19500 (Gen), ME: 32000 (Gen)",
        "placements_avg": "₹5.6 LPA",
        "placements_highest": "₹41.0 LPA (Adobe)",
        "placements_pct": "94%",
        "recruiters": "Microsoft, Adobe, Wells Fargo, Amazon, TCS, John Deere",
        "scholarships": "JVD state full fee support, SVECW Merit Scholarships"
    },
    {
        "name": "G. Pulla Reddy Engineering College (GPREC), Kurnool",
        "location": "Kurnool, Rayalaseema, Andhra Pradesh",
        "website": "https://www.gprec.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 151-200 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 240, IT: 120, ECE: 240, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹70,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹64,000/year",
        "additional_charges": "Additional Charges: ₹7,000/year",
        "eligibility": "10+2 MPC with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE convenor counseling Category-A, Category-B via notifications",
        "cutoffs": "CSE: 6200 (Gen), CSE-AIML: 8200 (Gen), ECE: 12200 (Gen), EEE: 22000 (Gen), ME: 34000 (Gen)",
        "placements_avg": "₹5.1 LPA",
        "placements_highest": "₹21.0 LPA",
        "placements_pct": "89%",
        "recruiters": "TCS Ninja/Digital, Cognizant, Wipro, Capgemini, L&T, IBM",
        "scholarships": "G. Pulla Reddy Charities concessions, full JVD eligibility"
    },
    {
        "name": "Rajeev Gandhi Memorial College of Engineering and Technology (RGMCET), Nandyal",
        "location": "Nandyal, Kurnool District, Andhra Pradesh",
        "website": "https://www.rgmcet.edu.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 201-250 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, CSE-CS, ECE, EEE, ME, CE",
        "intake": "CSE: 180, ECE: 180, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹60,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹52,000/year",
        "additional_charges": "Additional Charges: ₹5,000/year",
        "eligibility": "10+2 MPC with group score 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "AP EAPCET web counseling, Management category direct application",
        "cutoffs": "CSE: 12500 (Gen), CSE-AIML: 16500 (Gen), ECE: 24500 (Gen), EEE: 38000 (Gen), ME: 52000 (Gen)",
        "placements_avg": "₹4.3 LPA",
        "placements_highest": "₹14.0 LPA",
        "placements_pct": "83%",
        "recruiters": "TCS, Wipro, Cognizant, Tech Mahindra, Infosys, Syntel",
        "scholarships": "RGM Merit concessions, government scholarship schemes under JVD"
    },
    {
        "name": "Vignan's Foundation for Science, Technology and Research (VFSTR), Guntur",
        "location": "Vadlamudi, Guntur District, Andhra Pradesh – 522213",
        "website": "https://www.vignan.ac.in",
        "accreditation": "AICTE Approved, Deemed University, NBA",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 85 (Engineering)",
        "type": "Private Deemed University",
        "courses": "B.Tech, M.Tech, B.Pharm, MBA, MCA, Ph.D",
        "branches": "CSE, CS-BS, CSE-AI&ML, CSE-Cyber Security, CSE-Data Science, CSE-IoT, IT, ECE, ECE-VLSI, Biomedical, Biotechnology, Bioinformatics, Agricultural, Chemical, Civil, EEE, Mechanical, Robotics & Automation, Food Technology, Textile Technology",
        "intake": "CSE: 600, ECE: 240, Biotech: 120, ME: 60",
        "fees": "B.Tech CSE/CS-BS/CSE-AI&ML/CSE-Cyber Security/CSE-Data Science/CSE-IoT/IT: ₹2,80,000/year | ECE/ECE-VLSI/Biomedical/Biotechnology/Bioinformatics: ₹2,00,000/year | Agricultural/Chemical/Civil/EEE/Mechanical/Robotics/Food Technology: ₹1,20,000/year | Textile Technology: ₹1,00,000/year | Admission Fee (1st Year, Non-Refundable): ₹20,000",
        "hostel_fee": "Hostel Fee: ₹85,000 to ₹1,15,000/year",
        "additional_charges": "Admission Fee (1st Year, Non-Refundable): ₹20,000",
        "eligibility": "10+2 MPC with minimum 60% aggregate marks",
        "accepted_exams": "V-SAT, JEE Main, AP EAPCET",
        "admission_process": "V-SAT exam counseling, direct admission for EAPCET/JEE merit students",
        "cutoffs": "AP EAPCET (MPC) Rank below 10000: 75% scholarship, 10001–20000: 50%, 20001–35000: 25%, 35001–40000: 10%; V-SAT Rank 1–50: 75%, 51–200: 50%, 201–2000: 25%; JEE Main above 95%ile: 75%, 89–94.9: 50%, 80–88.9: 25%, 70–79.9: 10%",
        "placements_avg": "₹6.4 LPA",
        "placements_highest": "₹44.0 LPA",
        "placements_pct": "84%",
        "recruiters": "TCS, Cognizant, Accenture, Infosys, Wipro, Deloitte, IBM, Capgemini",
        "scholarships": "V-SAT Merit Scholarships (Rank 1–50: 75%, 51–200: 50%, 201–2000: 25%); AP EAPCET Rank below 10000: 75%, 10001–20000: 50%, 20001–35000: 25%, 35001–40000: 10%; JEE Main 95+%ile: 75%; AP Fee Reimbursement; SC/ST/BC/EWS Scholarships; Merit-Based Fee Concessions; Sports Scholarships"
    },
    {
        "name": "Raghu Engineering College, Visakhapatnam",
        "location": "Bheemunipatnam, Visakhapatnam, Andhra Pradesh",
        "website": "https://www.raghuenggcollege.com",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 251-300 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech",
        "branches": "CSE, CSE-AI&ML, CSE-DS, CSE-CS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 240, IT: 120, ECE: 240, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹62,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹60,000/year",
        "additional_charges": "Additional Charges: ₹6,000/year",
        "eligibility": "10+2 MPC with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE online convenor web option entry",
        "cutoffs": "CSE: 12200 (Gen), CSE-AIML: 15800 (Gen), ECE: 24000 (Gen), EEE: 39000 (Gen), ME: 55000 (Gen)",
        "placements_avg": "₹4.1 LPA",
        "placements_highest": "₹16.0 LPA",
        "placements_pct": "82%",
        "recruiters": "Infosys, Wipro, Cognizant, AWS, TCS, Capgemini, Mindtree",
        "scholarships": "JVD government reimbursement eligibility, Raghu Group merit concessions"
    },
    {
        "name": "Vignan's Institute of Information Technology (VIIT), Visakhapatnam",
        "location": "Duvvada, Visakhapatnam, Andhra Pradesh",
        "website": "https://vignaniit.edu.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade (CGPA 3.41/4.0)",
        "nirf": "NIRF Rank: 201-250 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 240, IT: 120, ECE: 240, EEE: 120, ME: 60",
        "fees": "B.Tech: ₹63,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹58,000/year",
        "additional_charges": "Additional Charges: ₹6,500/year",
        "eligibility": "10+2 MPC with group average of 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE Category-A counseling, direct Category-B seats",
        "cutoffs": "CSE: 9800 (Gen), CSE-AIML: 12800 (Gen), ECE: 18500 (Gen), EEE: 32000 (Gen), ME: 46000 (Gen)",
        "placements_avg": "₹4.5 LPA",
        "placements_highest": "₹22.0 LPA",
        "placements_pct": "86%",
        "recruiters": "TCS Digital, Cognizant, Wipro, Capgemini, Accenture, Infosys",
        "scholarships": "JVD reimbursement schemes, Vignan trust merit scholarship"
    },
    {
        "name": "Seshadri Rao Gudlavalleru Engineering College, Gudlavalleru",
        "location": "Krishna District, Gudlavalleru, Andhra Pradesh",
        "website": "https://www.gecgudlavalleru.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 201-250 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 240, IT: 120, ECE: 240, EEE: 120, ME: 60",
        "fees": "B.Tech: ₹67,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹56,000/year",
        "additional_charges": "Additional Charges: ₹5,000/year",
        "eligibility": "10+2 MPC with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Convenor counseling Category-A web entries",
        "cutoffs": "CSE: 10500 (Gen), CSE-AIML: 13500 (Gen), ECE: 20500 (Gen), EEE: 35000 (Gen), ME: 49000 (Gen)",
        "placements_avg": "₹4.3 LPA",
        "placements_highest": "₹16.0 LPA",
        "placements_pct": "84%",
        "recruiters": "Wipro, Cognizant, Mindtree, TCS, Capgemini, L&T Infotech",
        "scholarships": "JVD government reimbursement benefits, College merit incentives"
    },
    {
        "name": "Bapatla Engineering College (BEC), Bapatla",
        "location": "Bapatla, Guntur District, Andhra Pradesh",
        "website": "http://www.becbapatla.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 251-300 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MCA",
        "branches": "CSE, CSE-AI&ML, IT, ECE, EEE, ME, CE, Cyber Security",
        "intake": "CSE: 180, IT: 120, ECE: 180, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹65,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹52,000/year",
        "additional_charges": "Additional Charges: ₹5,500/year",
        "eligibility": "10+2 MPC with group average of 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Admissions primarily through AP EAPCET counseling (70%)",
        "cutoffs": "CSE: 12000 (Gen), CSE-AIML: 15000 (Gen), ECE: 23000 (Gen), EEE: 37000 (Gen), ME: 50000 (Gen)",
        "placements_avg": "₹4.2 LPA",
        "placements_highest": "₹15.0 LPA",
        "placements_pct": "81%",
        "recruiters": "TCS Ninja, Wipro, Capgemini, Infosys, Tech Mahindra",
        "scholarships": "JVD scheme eligible, Bapatla Education Society Merit concessions"
    },
    {
        "name": "QIS College of Engineering and Technology, Ongole",
        "location": "Ongole, Prakasam District, Andhra Pradesh",
        "website": "https://www.qiscet.edu.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 251-300 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 240, IT: 120, ECE: 180, EEE: 120",
        "fees": "B.Tech: ₹55,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹48,000/year",
        "additional_charges": "Additional Charges: ₹4,500/year",
        "eligibility": "10+2 MPC with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE state counseling online option entry",
        "cutoffs": "CSE: 15000 (Gen), CSE-AIML: 19000 (Gen), ECE: 28000 (Gen), EEE: 42000 (Gen), ME: 58000 (Gen)",
        "placements_avg": "₹3.8 LPA",
        "placements_highest": "₹12.0 LPA",
        "placements_pct": "78%",
        "recruiters": "TCS, Wipro, Cognizant, HCL, Tech Mahindra, Syntel",
        "scholarships": "JVD scheme eligible, QIS Trust concessions for financially backward students"
    },
    {
        "name": "PACE Institute of Technology and Sciences, Ongole",
        "location": "Ongole, Prakasam District, Andhra Pradesh",
        "website": "https://www.pace.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade (CGPA 3.32/4.0)",
        "nirf": "NIRF Rank: 251-300 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, IT, ECE, EEE, ME, CE, Automobile",
        "intake": "CSE: 180, IT: 120, ECE: 180, EEE: 120",
        "fees": "B.Tech: ₹58,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹50,000/year",
        "additional_charges": "Additional Charges: ₹5,000/year",
        "eligibility": "10+2 MPC with 45% in groups",
        "accepted_exams": "AP EAPCET",
        "admission_process": "70% seat allocation via state counseling portal, 30% management",
        "cutoffs": "CSE: 18000 (Gen), CSE-AIML: 22000 (Gen), ECE: 32000 (Gen), EEE: 48000 (Gen), ME: 62000 (Gen)",
        "placements_avg": "₹3.9 LPA",
        "placements_highest": "₹14.0 LPA",
        "placements_pct": "80%",
        "recruiters": "Cognizant, TCS, Wipro, Capgemini, HCL, Mindtree",
        "scholarships": "JVD reimbursement schemes, PACE merit concessions"
    },
    {
        "name": "Narayana Engineering College, Nellore",
        "location": "Nellore, Andhra Pradesh",
        "website": "https://www.necn.ac.in",
        "accreditation": "AICTE Approved, NBA Accredited (CSE, ECE)",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 251-300 Band",
        "type": "Private",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, IT, ECE, EEE, ME, CE",
        "intake": "CSE: 180, IT: 60, ECE: 180, EEE: 60",
        "fees": "B.Tech: ₹58,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹55,000/year",
        "additional_charges": "Additional Charges: ₹6,000/year",
        "eligibility": "10+2 MPC with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE state counseling online option entry",
        "cutoffs": "CSE: 15500 (Gen), CSE-AIML: 19500 (Gen), ECE: 26000 (Gen), EEE: 40000 (Gen), ME: 56000 (Gen)",
        "placements_avg": "₹4.0 LPA",
        "placements_highest": "₹15.0 LPA",
        "placements_pct": "82%",
        "recruiters": "TCS, Wipro, Cognizant, Capgemini, NTT Data, HCL",
        "scholarships": "JVD scheme eligible, Narayana Trust concessions for merit students"
    },
    {
        "name": "Audisankara College of Engineering and Technology, Gudur",
        "location": "Gudur, Nellore District, Andhra Pradesh",
        "website": "https://www.audisankara.ac.in",
        "accreditation": "AICTE Approved, Autonomous, NBA",
        "naac": "NAAC A+ Grade",
        "nirf": "NIRF Rank: 251-300 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, ECE, EEE, ME, CE",
        "intake": "CSE: 180, ECE: 180, EEE: 120",
        "fees": "B.Tech: ₹55,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹50,000/year",
        "additional_charges": "Additional Charges: ₹4,500/year",
        "eligibility": "10+2 MPC with 45% minimum",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE Convenor Counseling (Category-A)",
        "cutoffs": "CSE: 20000 (Gen), CSE-AIML: 25000 (Gen), ECE: 35000 (Gen), EEE: 50000 (Gen)",
        "placements_avg": "₹3.8 LPA",
        "placements_highest": "₹12.0 LPA",
        "placements_pct": "80%",
        "recruiters": "TCS, LTI, Cognizant, Wipro, Capgemini, HCL",
        "scholarships": "JVD scheme eligible, Audisankara Merit waivers"
    },
    {
        "name": "Geethanjali Institute of Science and Technology (GIST), Nellore",
        "location": "Nellore, Andhra Pradesh",
        "website": "http://www.gist.edu.in",
        "accreditation": "AICTE Approved, NBA (CSE, ECE, EEE)",
        "naac": "NAAC A Grade",
        "type": "Private",
        "courses": "B.Tech",
        "branches": "CSE, CSE-AI&ML, ECE, EEE, ME, CE",
        "intake": "CSE: 180, ECE: 120, EEE: 60",
        "fees": "B.Tech: ₹50,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹45,000/year",
        "additional_charges": "Additional Charges: ₹4,000/year",
        "eligibility": "10+2 MPC with 45% group score",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Convenor state counseling list selection",
        "cutoffs": "CSE: 18000 (Gen), CSE-AIML: 22000 (Gen), ECE: 30000 (Gen), EEE: 45000 (Gen)",
        "placements_avg": "₹3.7 LPA",
        "placements_highest": "₹10.0 LPA",
        "placements_pct": "79%",
        "recruiters": "Wipro, Cognizant, TCS, Capgemini, Infosys, Syntel",
        "scholarships": "JVD government reimbursement, GIST Merit awards"
    },
    {
        "name": "NBKR Institute of Science and Technology, Vidyanagar",
        "location": "Vidyanagar, Nellore District, Andhra Pradesh",
        "website": "http://www.nbkrist.org",
        "accreditation": "AICTE Approved, Autonomous, NBA (All Branches)",
        "naac": "NAAC A Grade",
        "nirf": "NIRF Rank: 201-250 Band",
        "type": "Private Autonomous",
        "courses": "B.Tech",
        "branches": "CSE, CSE-AI&ML, ECE, EEE, ME, CE",
        "intake": "CSE: 180, ECE: 180, EEE: 120, ME: 120",
        "fees": "B.Tech: ₹68,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹55,000/year",
        "additional_charges": "Additional Charges: ₹6,000/year",
        "eligibility": "10+2 MPC with 45% in groups",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE state counseling online option entry",
        "cutoffs": "CSE: 12000 (Gen), CSE-AIML: 15500 (Gen), ECE: 22000 (Gen), EEE: 34000 (Gen), ME: 48000 (Gen)",
        "placements_avg": "₹4.5 LPA",
        "placements_highest": "₹16.0 LPA",
        "placements_pct": "84%",
        "recruiters": "TCS Digital, Cognizant, Wipro, Capgemini, HCL, Mindtree",
        "scholarships": "JVD reimbursement schemes, NBKR trust merit scholarship"
    },
    {
        "name": "Santhiram Engineering College, Nandyal",
        "location": "Nandyal, Kurnool District, Andhra Pradesh",
        "website": "https://www.srec.ac.in",
        "accreditation": "AICTE Approved, NBA Accredited (CSE, ECE)",
        "naac": "NAAC A Grade",
        "type": "Private",
        "courses": "B.Tech, MBA, MCA",
        "branches": "CSE, CSE-AI&ML, CSE-DS, ECE, EEE",
        "intake": "CSE: 180, ECE: 120, EEE: 60",
        "fees": "B.Tech: ₹45,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹45,000/year",
        "additional_charges": "Additional Charges: ₹3,500/year",
        "eligibility": "10+2 MPC with 45% minimum group score",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Category-A state web option counseling",
        "cutoffs": "CSE: 25000 (Gen), CSE-AIML: 32000 (Gen), ECE: 45000 (Gen), EEE: 60000 (Gen)",
        "placements_avg": "₹3.5 LPA",
        "placements_highest": "₹8.0 LPA",
        "placements_pct": "75%",
        "recruiters": "TCS Ninja, Wipro, Capgemini, Infosys, Tech Mahindra",
        "scholarships": "JVD government scheme, Santhiram Merit concessions"
    },
    {
        "name": "Anantha Lakshmi Institute of Technology and Sciences, Anantapur",
        "location": "Anantapur, Andhra Pradesh",
        "website": "http://www.alits.ac.in",
        "accreditation": "AICTE Approved, affiliated to JNTUA",
        "naac": "NAAC B+ Grade",
        "type": "Private",
        "courses": "B.Tech, MBA",
        "branches": "CSE, CSE-AI&ML, ECE, EEE, ME, CE",
        "intake": "CSE: 120, ECE: 120, EEE: 60",
        "fees": "B.Tech: ₹40,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹42,000/year",
        "additional_charges": "Additional Charges: ₹3,000/year",
        "eligibility": "10+2 MPC stream with minimum 45% group average",
        "accepted_exams": "AP EAPCET",
        "admission_process": "Convenor state counseling list selection",
        "cutoffs": "CSE: 35000 (Gen), CSE-AIML: 45000 (Gen), ECE: 60000 (Gen), EEE: 80000 (Gen)",
        "placements_avg": "₹3.2 LPA",
        "placements_highest": "₹7.0 LPA",
        "placements_pct": "70%",
        "recruiters": "Wipro, Cognizant, Hexaware, Hyundai, TCS, Amazon",
        "scholarships": "JVD state full fee support, ALITS Merit Scholarships"
    },
    {
        "name": "Srinivasa Ramanujan Institute of Technology (SRIT), Anantapur",
        "location": "Anantapur, Andhra Pradesh",
        "website": "https://www.srit.ac.in",
        "accreditation": "AICTE Approved, NBA (CSE, ECE)",
        "naac": "NAAC A Grade",
        "type": "Private Autonomous",
        "courses": "B.Tech, M.Tech",
        "branches": "CSE, CSE-AI&ML, ECE, EEE, ME, CE",
        "intake": "CSE: 180, ECE: 120, EEE: 60",
        "fees": "B.Tech: ₹55,000/year (Convenor Quota)",
        "hostel_fee": "Hostel Fee: ₹48,000/year",
        "additional_charges": "Additional Charges: ₹4,000/year",
        "eligibility": "10+2 MPC with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE state counseling online option entry",
        "cutoffs": "CSE: 20000 (Gen), CSE-AIML: 25000 (Gen), ECE: 35000 (Gen), EEE: 55000 (Gen)",
        "placements_avg": "₹3.9 LPA",
        "placements_highest": "₹12.0 LPA",
        "placements_pct": "81%",
        "recruiters": "TCS Ninja, Infosys, Cognizant, Wipro, Capgemini, SLK Software",
        "scholarships": "JVD eligibility, SRIT Merit concessions"
    },
    {
        "name": "JNTUA College of Engineering, Pulivendula",
        "location": "Pulivendula, Kadapa District, Andhra Pradesh",
        "website": "https://www.jntuacep.ac.in",
        "accreditation": "AICTE Approved, NBA Accredited",
        "naac": "NAAC A Grade",
        "type": "Government",
        "courses": "B.Tech, M.Tech",
        "branches": "CSE, ECE, EEE, ME, CE",
        "intake": "CSE: 60, ECE: 60, EEE: 60, ME: 60, CE: 60",
        "fees": "CSE/ECE/EEE: ₹10,000/year (Regular)",
        "hostel_fee": "Hostel Fee: ₹25,000/year",
        "additional_charges": "Additional Charges: ₹3,500/year",
        "eligibility": "10+2 MPC stream with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE Single Window Counseling",
        "cutoffs": "CSE: 5000 (Gen), ECE: 8500 (Gen), EEE: 15000 (Gen), ME: 25000 (Gen), CE: 32000 (Gen)",
        "placements_avg": "₹4.8 LPA",
        "placements_highest": "₹14.0 LPA",
        "placements_pct": "78%",
        "recruiters": "TCS, Cognizant, Accenture, Hexaware, Hyundai",
        "scholarships": "Full State Fee Reimbursement, Jagananna Vasathi Deevena support"
    },
    {
        "name": "JNTUK College of Engineering, Vizianagaram",
        "location": "Vizianagaram, Andhra Pradesh",
        "website": "https://www.jntukucev.ac.in",
        "accreditation": "AICTE Approved, NBA Accredited",
        "naac": "NAAC A Grade",
        "type": "Government",
        "courses": "B.Tech, M.Tech",
        "branches": "CSE, ECE, EEE, ME, CE, IT",
        "intake": "CSE: 60, ECE: 60, EEE: 60, ME: 60, CE: 60",
        "fees": "CSE/ECE/EEE: ₹10,000/year (Regular)",
        "hostel_fee": "Hostel Fee: ₹25,000/year",
        "additional_charges": "Additional Charges: ₹3,500/year",
        "eligibility": "10+2 MPC stream with 45%",
        "accepted_exams": "AP EAPCET",
        "admission_process": "APSCHE Single Window Counseling",
        "cutoffs": "CSE: 3000 (Gen), ECE: 6500 (Gen), EEE: 12000 (Gen), ME: 20000 (Gen), CE: 28000 (Gen)",
        "placements_avg": "₹5.0 LPA",
        "placements_highest": "₹16.0 LPA",
        "placements_pct": "80%",
        "recruiters": "TCS, Cognizant, Accenture, Hexaware, L&T",
        "scholarships": "Full State Fee Reimbursement, Jagananna Vasathi Deevena support"
    }
]

# Function to generate 1-page PDF for a college
def generate_pdf(college, path):
    pdf_filename = os.path.join(path, f"{college['name'].split('(')[0].strip().replace(' ', '_').replace(',', '')}.pdf")
    doc = SimpleDocTemplate(pdf_filename, pagesize=letter,
                            rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    
    styles = getSampleStyleSheet()
    
    # Custom Styles to fit 1 page
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=15,
        textColor=colors.HexColor('#1E3A8A'), # Dark Blue
        spaceAfter=6,
        leading=18
    )
    
    section_style = ParagraphStyle(
        'SectionStyle',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=11,
        textColor=colors.HexColor('#0F766E'), # Teal
        spaceBefore=6,
        spaceAfter=3,
        leading=14
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        textColor=colors.HexColor('#374151'), # Dark gray
        leading=12
    )

    bold_body_style = ParagraphStyle(
        'BoldBodyStyle',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    
    story = []
    
    # Title
    story.append(Paragraph(college['name'], title_style))
    story.append(Paragraph(f"<b>Location:</b> {college['location']} | <b>Website:</b> {college['website']}", body_style))
    story.append(Paragraph(f"<b>Accreditation:</b> {college['accreditation']} | <b>NAAC:</b> {college['naac']} | <b>Rank:</b> {college.get('nirf', 'N/A')}", body_style))
    story.append(Paragraph(f"<b>Type:</b> {college['type']}", body_style))
    story.append(Spacer(1, 4))
    
    # Academic & Intake
    story.append(Paragraph("Academic Information", section_style))
    story.append(Paragraph(f"<b>Courses:</b> {college['courses']}", body_style))
    story.append(Paragraph(f"<b>Branches Offered:</b> {college['branches']}", body_style))
    story.append(Paragraph(f"<b>Intake Capacity:</b> {college['intake']}", body_style))
    story.append(Spacer(1, 4))

    # Fee Information
    story.append(Paragraph("Fee Structure & Facilities", section_style))
    fee_data = [
        [Paragraph(f"<b>Branch-wise Fees:</b> {college['fees']}", body_style)],
        [Paragraph(f"<b>Hostel Fees:</b> {college['hostel_fee']}", body_style)],
        [Paragraph(f"<b>Additional Charges:</b> {college['additional_charges']}", body_style)]
    ]
    fee_table = Table(fee_data, colWidths=[7.2 * inch])
    fee_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F3F4F6')),
        ('PADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E5E7EB'))
    ]))
    story.append(fee_table)
    story.append(Spacer(1, 4))
    
    # Admissions
    story.append(Paragraph("Admissions & Cutoffs", section_style))
    story.append(Paragraph(f"<b>Eligibility:</b> {college['eligibility']}", body_style))
    story.append(Paragraph(f"<b>Accepted Exams:</b> {college['accepted_exams']} | <b>Process:</b> {college['admission_process']}", body_style))
    story.append(Paragraph(f"<b>Cutoff Ranks (Convenor Quota AP EAPCET General):</b> {college['cutoffs']}", bold_body_style))
    story.append(Spacer(1, 4))
    
    # Placements
    story.append(Paragraph("Placements", section_style))
    story.append(Paragraph(f"<b>Average Package:</b> {college['placements_avg']} | <b>Highest Package:</b> {college['placements_highest']} | <b>Placement %:</b> {college['placements_pct']}", body_style))
    story.append(Paragraph(f"<b>Top Recruiters:</b> {college['recruiters']}", body_style))
    story.append(Spacer(1, 4))
    
    # Scholarships
    story.append(Paragraph("Scholarships & Financial Aid", section_style))
    story.append(Paragraph(college['scholarships'], body_style))
    
    doc.build(story)
    print(f"Generated PDF for {college['name']}")

if __name__ == "__main__":
    kb_path = "pdf_kb"
    os.makedirs(kb_path, exist_ok=True)
    for col in colleges:
        generate_pdf(col, kb_path)
    print(f"Completed! Generated {len(colleges)} college PDFs in '{kb_path}' directory.")
